# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a901abfac46626af3462b3deac49a94bbc841f7a8ca67927b11d0208c9bbdeb679072da9e34a58c11236905687796e9da2e0e4f7c204899531b17959440e8c9e

test:
  secret_key_base: 3620fe56a27b49944ebbe2864a7cf89421c86e289792d313b48d8b386c9adc4fc66fd5299905f924f295c3d8713e2890113447399558d5f740206dc01b56ed3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
